export {COUNT_ITEMS_ON_PAGE, MAX_LENGTH_TEXT, MAX_LENGTH_TITLE, MIN_LENGTH_TEXT, MIN_LENGTH_TITLE};

const COUNT_ITEMS_ON_PAGE = 2;
const MIN_LENGTH_TITLE = 3;
const MAX_LENGTH_TITLE = 50;
const MIN_LENGTH_TEXT = 3;
const MAX_LENGTH_TEXT = 500;
